name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Step 1 - Go version
        run: go version

      - name: Step 2 - Go build
        run: go build -v ./...
